version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.9.5-eclipse-temurin-21-alpine
      - image: seleniarm/standalone-chromium
        environment:
          CHROME_HEADLESS: 1
    circleci_ip_ranges: true

    steps:
      - checkout

      - run:
          name: Build and Run tests
          command:
            mvn test -Dbrowser=remote-chrome -Dspring.profiles.active="staging" -Dtest=uk.gov.justice.digital.hmpps.vsip.suites.RunSuite