version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11
      - image: seleniarm/standalone-chromium
        environment:
          CHROME_HEADLESS: 1
    circleci_ip_ranges: true

    steps:
      - checkout

      - run:
          name: Build and Run tests
          command:
            mvn test -Dbrowser=remote-chrome -Denvironment="STAGING"